specVersion: 1.0.0
name: terra-subql-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node-Arweave'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your Cosmos based
  SubQuery project
repository: https://github.com/subquery/terra-subql-starter
schema:
  file: ./schema.graphql
network:
  chainId: cosmoshub-4
  endpoint: http://139.59.51.59:1984

dataSources:
  - kind: arweave/Runtime
    startBlock: 500000
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: arweave/BlockHandler
        - handler: handleTransaction
          kind: arweave/TransactionHandler
          filter:
            owner: "sf5ei-je-nwohfmQHyB8kvyhuOAhQlW5GMC7Pmoyss8"
